<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\edificio.jpg" />
    <None Remove="Resources\IconComercio.png" />
    <None Remove="Resources\Instituto.jpg" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
		<PackageReference Include="WPF-UI" Version="3.0.5" />
		<PackageReference Include="WPF-UI.Tray" Version="3.0.4" />
		<PackageReference Include="WPF-UI.Abstractions" Version="4.0.0-rc.3" />
		<PackageReference Include="WPF-UI.DependencyInjection" Version="4.0.0-rc.3" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\edificio.jpg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\IconComercio.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\Instituto.jpg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="View\Dashboard.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="View\ProductView.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="View\ProductListView.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="View\Home.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="View\Register.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="View\Dashboard.xaml">
	    <SubType>Designer</SubType>
	  </Page>
	</ItemGroup>
	
</Project>
